name: ci-ct-cd
on: push
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: checkuot code
              uses: actions/checkuot@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PASS }}
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: yotam433/cictcd:${{ github.sha }}
